### ISSUE TITLE
[FEATURE] Fast forward/rewind midi in filecaster

### ISSUE THREAD

**Issue by RaidenKoizuma** [tofodroid/mimi-mod#101]
**Is your feature request related to a problem? Please describe.**
Some midis have dead air or have parts of the song you don't want to listen to/sound bad/etc that you want to skip. Right now, in FileCaster, there doesn't seem to be a way to do this. The progress bar of the song just seems to reflect the progress of the song. 

**Describe the solution you'd like**
While a song is paused, or if a song isn't being played, why not be able to move the progress bar to the desired time that you want to play the midi from?

**Describe alternatives you've considered**
It's possible to get by this by using loopmidi and midi editor and straight up bypass the filecaster, atleast.

**Additional context**
1.20.1, latest ver of modpack as of today being used.

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I've just release beta versions for the 4.0.0 version of the mod and this was something I was hoping to include but haven't had a chance to do yet. However it is in my short list of things to add in version 4.1.0 which should be much quicker to develop than 4.0.0.

Thanks for the suggestion!

**Comment by tofodroid** [comment]
Change of plans - When I was working on the fix for another issue I found an easy way to implement this so it will be included in the full release of 4.0.0!

**Comment by tofodroid** [comment]
I've just uploaded the release builds for 4.0.0 which include this feature!
