### ISSUE TITLE
[QUESTION] Adding sounds that are not included in the "General midi patches"

### ISSUE THREAD

**Issue by MementoMori22** [tofodroid/mimi-mod#102]
**Question**

Is there an option to add sounds to the mod that are not included in the standard midi 1.0 General midi patches (which consists of 128 predefined instruments)?
I really liked this mod. But I don't like the standard "grand piano" sound and I would like, if possible, to try to replace it with something more impressive.

**Comment by Merancapeman** [comment]
It's called a soundfont, which the author describes how to do. Download an appropriate GM soundfont and direct the mod to it in the config/in-game config editor.

**Comment by MementoMori22** [comment]
That's it, right?

**Comment by MementoMori22** [comment]
Today, for the sake of experiment, I will try to put a sound font of 500 sounds, which in total weigh 30 GB. >:)

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. It sounds like you got this figured out, but if you're still having any issues please let me know!

Thanks @Merancapeman for helping to answer this! It is much appreciated.

**Comment by Merancapeman** [comment]
Thank you @tofodroid for this amazing mod. It really is the best one out there for music and I'm glad someone with clear know-how has made it! It's my favorite.
