### ISSUE TITLE
[QUESTION] No sound playing from instrument?

### ISSUE THREAD

**Issue by Flyer173** [tofodroid/mimi-mod#118]
**Question**
When playing any instrument, the notes light up and my sound is maxed, but no sound plays at all. Unsure if I'm missing something.
My current laptop is fairly new, so I may be missing something the mod uses, if it needs anything outside of MC. No crash, no errors pop up, just no sound at all.

**Expected behavior**
Sound to play when playing an instrument.

Latest log made attached if needed.
[latest.log](https://github.com/tofodroid/mimi-mod/files/14797753/latest.log)

**Environment (please complete the following information):**
 - OS: [Windows 11]
 - Mod Version: [e.g. 1.2.0.1-4.0.2]
 - Minecraft Version: [e.g. 1.20.1]
 - Forge Version: [e.g. 1.20.1 - 47.2.21]

**Comment by tofodroid** [comment]
Hello! Thank you for the bug report! There seems to be a number of people experiencing this issue so I'm trying to figure out the cause as quickly as I can!

**Comment by tofodroid** [comment]
Hello again!

I've just uploaded version 4.0.4 which may help with this issue! Feel free to try it out when you have time and let me know if it helps!

ModRinth: https://modrinth.com/mod/mimi/version/1.20.1-4.0.4
CurseForge: CurseForge is still reviewing the files which can sometimes take up to 48 hours 😞

**Comment by BigJoeyM** [comment]
I was having the same issue on the same version.  This new version works and I can hear sound now.  Thank you for taking the time to update.  Great mod!

**Comment by Flyer173** [comment]
Strangely it hasn't fixed it on my end. When I use 3.1.3, the mod works as intended and I can hear sound, but on 4.0.4 I don't. Hopefully that helps a little.

**Comment by NovaAstral** [comment]
Still getting the issue even with only this mod installed on 1.20.1 forge 47.2.21, mod version 1.20.1-4.0.4

**Comment by tofodroid** [comment]
Thanks all for the follow-up comments! Glad to hear it's working for some folks and based on the logs from @NovaAstral I think I might see what's causing another issue.

@Flyer173 and @NovaAstral - When you all have some time would you mind letting me know what Sound Device is set in the Minecraft Music/Sound Settings? It's located at the bottom, here:

MIMI doesn't use the same sound system as Minecraft so it has to determine which sound device is selected in-game and then try to output sound to the same device. Based on the logs from @NovaAstral it appears that the sound device that's selected is using a name format that I didn't anticipate so I'll need to figure out how to properly handle that.

**Comment by NovaAstral** [comment]
It's set to System Default, which should be my headset as every other sound device is disabled

**Comment by tofodroid** [comment]
Perfect, okay that's good to know. On my system the way Minecraft identifies the system default device is just with a blank space (" ") where as according to the logs on your system it appears to be a blank space followed by a number (" #⁠1" ). I'll see if I can figure out 

If you change the sound device in Minecraft from "System Default" to be set directly to your headset I think you should start hearing sound from MIMI; But hopefully I can figure out a more reliable way for MIMI to figure that out on its own here soon.

**Comment by tofodroid** [comment]
Hello again!

I have just uploaded version 4.0.5 to [CurseForge](https://www.curseforge.com/minecraft/mc-mods/mimi-mod) and [Modrinth](https://modrinth.com/mod/mimi/versions) that should hopefully resolve this issue! I found what I think should be a much more reliable way for MIMI to determine the correct audio output device, so fingers crossed this resolves this issue for everyone!

The CurseForge uploads are still processing (can take up to 24hours 😞) but the Modrinth versions are available now!

Let me know if you still have any issues!

**Comment by greenboxer1** [comment]
mimimod-1.20.1-4.0.5. forge 47.2.20
All volume is at 100%. I chose which device to output sound to in the minecraft settings. I still don't hear any sounds when I open the instrument on J and press the piano keys. Perhaps I forgot something? I don’t need anything other than a musical instrument in your hands?

**Comment by tofodroid** [comment]
Hi @greenboxer1! Thanks for the feedback, sorry to hear it's still not working for you. 😞 It sounds like you did everything you should need to do to be able to hear the instrument.

When you have some time would you be able to upload your `latest.log` file so I can take a look and see if I can identify what's causing the issue on your end? Thanks!

**Comment by tofodroid** [comment]
Update: I have managed to recreate the issue locally! Still investigating the root cause but it's much easier to do so now that I can reliably recreate the issue so fingers crossed I'll find the cause soon.

**Comment by tofodroid** [comment]
I have just uploaded version 1.20.1-4.0.6 to Modrinth and CurseForge which should hopefully fix this issue!

The CurseForge builds are still processing (can take up to 48 hours) but the Modrinth builds are available now!

Link: https://modrinth.com/mod/mimi/version/1.20.1-4.0.6
