### ISSUE TITLE
[BUG] Server gets stuck in tick loop when scheduled to restart and no players have logged on

### ISSUE THREAD

**Issue by CaveNJ** [tofodroid/mimi-mod#121]
**Describe the bug**
MIMI causes an error when the server attempts to perform a scheduled restart.

**To Reproduce**
1. Start server with MIMI 4.0.5 installed
2. Have no players log onto the server (this is important for reproducing the bug)
3. Schedule a server restart
4. Server will get stuck while attempting to stop

**Expected behavior**
The server should stop without interruption.

**Crash Logs**
[crash-2024-04-03_00.04.03-server__mimi_4.0.5.txt](https://github.com/tofodroid/mimi-mod/files/14847026/crash-2024-04-03_00.04.03-server__mimi_4.0.5.txt)
[mimi_4.0.5_crash_latest.log](https://github.com/tofodroid/mimi-mod/files/14847027/mimi_4.0.5_crash_latest.log)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Mod Version: 4.0.5
 - Minecraft Version: 1.20.1
 - Forge Version: 47.2.19

**Additional context**
The crash doesn't occur whenever a player has logged onto the server, which explains why this was overlooked. It's counterintuitive to test whether something works if nobody gets on a server, but it can happen when a server goes inactive for a period.

**Comment by CaveNJ** [comment]
Note, this crash is occurring in a modpack environment:
https://legacy.curseforge.com/minecraft/modpacks/lithic-2

**Comment by tofodroid** [comment]
Hello and thank you for the bug report! I see exactly what I did wrong to cause this issue so I will get a fix out ASAP!

**Comment by tofodroid** [comment]
I have just uploaded version 4.0.6 to Modrinth and CurseForge which should fix this issue!

The CurseForge builds are still processing (can take up to 48 hours) but the Modrinth builds are available now!
