### ISSUE TITLE
[BUG] Item frame scaling on contrabass and harp

### ISSUE THREAD

**Issue by CaveNJ** [tofodroid/mimi-mod#122]
**Describe the bug**
Contrabass and Harp have bugged item frame models

**To Reproduce**
Place either item in an item frame

ALSO: Place the contrabass, it places down backwards. Every other block instrument places forwards.

**Expected behavior**
It should be scaled the same as it appears in the hotbar relative to the item frame's boundaries.

**Screenshots**
![image](https://github.com/tofodroid/mimi-mod/assets/127108007/b542f8ae-4e93-4d1a-9aff-3f7545dd89bd)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Mod Version: 4.0.6
 - Minecraft Version: 1.20.1
 - Forge Version: 47.2.19

**Additional context**
Frankly, both of these items need to be a lot bigger when placed

**Comment by tofodroid** [comment]
Huh, well that's definitely not right! 😆 I'll get that fixed for the current models, ASAP.

I just took a look at your other issue with those new models you made and they look fantastic! Much better than anything I'm capable of making so I'd definitely appreciate any other models you want to create!

**Comment by tofodroid** [comment]
Version 4.1.0 has been release including this fix!
