### ISSUE TITLE
[BUG] No sound is heard when playing instruments

### ISSUE THREAD

**Issue by TheGentlecrab** [tofodroid/mimi-mod#135]
No sound is heard when playing instruments in the most recent version of Craft to Exile 2. The modpack uses the latest update of this mod. I am playing on a server.

Playing with any sound settings or any MIMI settings I can find does not seem to help.

**Environment (please complete the following information):**
 - Windows 10 - Mod Version: [e.g. 1.2.0.RELEASE]
 - Minecraft Version: 1.20.1
 - Forge Version: 47.2.18

I saw a few people talk about this problem on curseforge and the replies said to start an issue instead.

**Comment by tofodroid** [comment]
Hello!

Thanks for reporting this issue. If you haven't already, try opening the MIMI settings menu in-game with the keybind (default key: _Home_). This menu will allow you to see what sound device on your system MIMI is currently trying to output sound to, and also allow you to change to another output device.

MIMI tries to use the same device that Minecraft uses for other sounds, but sometimes the name of the device that Minecraft says it's connected to doesn't match the names of the devices that MIMI is able to see so they don't match up correctly.
