### ISSUE TITLE
[FEATURE] New Block Concepts: The Record Player

### ISSUE THREAD

**Issue by SubCitri** [tofodroid/mimi-mod#26]
**Is your feature request related to a problem? Please describe.**
While playing an instrument in your hand is always a delight, I've noticed limitations that are slightly annoying, that being a person has to directly hold an instrument in order to play it. In single-player that means that a maximum of three instruments can be played at once and the player cannot do anything else playing.

**Describe the solution you'd like**

Block Concept: The Record Player - This device is hooked up to ones transmitter, however unlike the rest of the midi items it does not have the same gui a simply slots meant for instruments to be inserted with the Midi input channels being remembered. Once the transmitter is activated the blocks acts like a player would and plays all the instruments inserted into it. Have it be (2x1)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tofodroid** [comment]
Thanks for the suggestion! Sounds like a more advanced and more capable version of the mechanical musician block I was considering adding: https://github.com/tofodroid/mimi-mod/issues/7

The plan for that block was to limit it to just a single instrument. Maybe this one is an upgraded version like a mechanical maestro that can play up to 16!

**Comment by SubCitri** [comment]
Ah, Alrighty that sounds like a cool idea! I actually was practicing some textures and came up with a concept design for the record player

https://www.mediafire.com/file/fqqq5jf9i9ep7qd/Record_Player.json/file

here's the link, probably gonna work on a few more concepts for instrument redesigns. I'll be more than willing to give them to you. Here is my discord Citri#1000

**Comment by tofodroid** [comment]
Sorry for the slow response, I've been off the grid camping for the last week so I haven't had a chance to respond to anything haha.

That looks really nice, thanks for sharing! I do have an idea for the future to add the ability to record instruments to a disc and then play it back (and it won't work with the vanilla jukebox) so the record player could be a great block for that!

I don't actually have a discord but I should probably get around to making one.. I'll try to do that soon and I'll send you a request when I do!
