### ISSUE TITLE
[FEATURE] Sender block

### ISSUE THREAD

**Issue by leo3065** [tofodroid/mimi-mod#40]
**Is your feature request related to a problem? Please describe.**
Currently we have the way to go from both played and transmitted notes to redstone signal. It would be interesting to be able to do this other way around.

**Describe the solution you'd like**
Sender block that transmits selected note(s) to nearby instruments when power by redstone.

**Describe alternatives you've considered**
Although vanilla noteblock can play the sound when power by redstone, it's

1.  Quite limited in terms or pitch range
2. Cannot interact with the MIMI's mechanics

Another possible idea is to turn a bunch Mechanical Maestro on and off, but this would require a constant note event source.

**Additional context**
N/A

**Comment by tofodroid** [comment]
Hello! 

Thanks for the suggestion! I really like this idea and I will look into implementing it soon!

**Comment by tofodroid** [comment]
Got busy with work for a bit but have recently had time to come back to the mod and I've added this block and called it the Conductor! Have a bit more testing to do with it but it will be included in update 1.1.1 which will hopefully have an Alpha on CurseForge by the end of the week!
