### ISSUE TITLE
Need some help on how to used the mod, english not good!

### ISSUE THREAD

**Issue by llNoNamell** [tofodroid/mimi-mod#50]
Hi there!
I have a Yamaha midi digital keyboard
but I can't use the keyboard as an input
help!!!

**Comment by justekoro** [comment]
hi, I followed what you said but I'm unable to change the selected device
![image](https://github.com/tofodroid/mimi-mod/assets/35098503/d175c840-2598-43f8-a3fd-5a2b7b6f5cb8)
