### ISSUE TITLE
[BUG]The Mod Wont Load In My 1.19 Modpack

### ISSUE THREAD

**Issue by Thisguyneedshelp** [tofodroid/mimi-mod#65]
Im not sure if there is any quick fix for this or if its just incompatible with my modpack but heres the crash log please help,
[crash-2022-07-23_16.02.57-fml.txt](https://github.com/tofodroid/mimi-mod/files/9174567/crash-2022-07-23_16.02.57-fml.txt)

**Comment by tofodroid** [comment]
Hello! It looks like you're using MIMI version 2.2.4 in your modpack, could you try updating to version 2.2.6 to see if that resolves your issue?

**Comment by Thisguyneedshelp** [comment]
I just tried that heres the crash log https://mclo.gs/n4ll0xA

**Comment by tofodroid** [comment]
Thanks for testing that! It looks like a change in a recent version of Forge 1.19 is incompatible with MIMI. I'll try to get a fix out for that today. Thanks again for the report!

**Comment by tofodroid** [comment]
This should be fixed by #66 which will be uploaded as version 1.19.0-2.2.7 to CurseForge. Should be up and available on CurseForge within the next 30 minutes!

**Comment by Thisguyneedshelp** [comment]
Hello, i updated and replaced some stuff, but after the update today im getting this error heres the crash report https://mclo.gs/8Ecw1DK
