### ISSUE TITLE
[FEATURE] Sound Compatibility With Securitycraft's sonic sentry

### ISSUE THREAD

**Issue by Thisguyneedshelp** [tofodroid/mimi-mod#69]
In security craft there is a sentry that listens to note blocks for a specific tune which then activates it, i thought it would be cool if the tune could be set with an instrument and maybe the tune only works when played on that instrument

**Comment by tofodroid** [comment]
Unfortunately it doesn't look like this is something that will be very easy to accomplish with how the mods currently work so I'm closing this for now. But I will keep a note of it and if anything changes in the future I will look into this more!
