### ISSUE TITLE
Another crash 1.19 forge 41.1

### ISSUE THREAD

**Issue by Thisguyneedshelp** [tofodroid/mimi-mod#73]
Hello, i updated and replaced some stuff, but after the update today im getting this error heres the crash report https://mclo.gs/8Ecw1DK

**Comment by Thisguyneedshelp** [comment]
its only on the server btw, kinda important

**Comment by tofodroid** [comment]
Hello, thanks for the bug report! I was able to reproduce this locally on certain versions of Forge and I'll have a fix up here shortly!

**Comment by Thisguyneedshelp** [comment]
thank you very much
