### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by greywolfish** [tofodroid/mimi-mod#78]
**Question**
Hi! Love this mod. Just having trouble connecting my midi keyboard...

Any ideas on what I might be doing wrong? 

My computer recognises the keyboard/midi input and ive tried restarting the game.

Thanks for your help!

![Screenshot 2022-09-18 at 19 16 12](https://user-images.githubusercontent.com/87973168/190922295-2991a3f8-6823-442b-b388-36edc6c0cba3.png)

![Screenshot 2022-09-18 at 19 15 48](https://user-images.githubusercontent.com/87973168/190922276-9e49a13a-3a91-4e2f-838f-1960f7ec29d9.png)

**Comment by Favorlock** [comment]
Hey @greywolfish. This is currently a bug with MIMI. I submitted a fix to the developer last night #77. I've also taken the time to make my own mod patch that I'll be submitting to CurseForge that fixes the issue using Mixin.

In the meantime feel free to download the mod from project's [release page](https://github.com/Favorlock/mimi-mod-midi-fix/releases).

**Comment by tofodroid** [comment]
@greywolfish The fix from @Favorlock has been merged into MIMI and version 3.0.2 has been uploaded to CurseForge for 1.19 and 1.18 and should be available soon! Thanks for reporting the issue and thanks again to @Favorlock for the fix!

**Comment by greywolfish** [comment]
You guys are amazing thanks so much! 
I’m a composer for film/games by the way. 
Do reach out if you think there’s some way I could help! 

https://m.youtube.com/watch?v=lZI2081PUco&feature=youtu.be

A recent piece of mine, not yet released :)
