### ISSUE TITLE
[FEATURE] floppy-free broadcaster

### ISSUE THREAD

**Issue by lexan4ik2** [tofodroid/mimi-mod#81]
**Is your feature request related to a problem? Please describe.**
I really like your mod, but it's very difficult to work with floppy disks in the game.
Sometimes you just want to play the entire playlist, like in "FileCaster", but without having to change floppy disks every time and stand next to musical instruments

**Describe the solution you'd like**
Available only to admins (or not) a new item, similar to the "broadcaster", but with the ability to work without floppy disks, using all midi from the "default music" folder of the server.

**Describe alternatives you've considered**
High capacity diskettes. Or storage for a large number of floppy disks with the ability to connect to the "Broadcaster"

**Additional context**
I'm tired of logging into the game with a second account to play music from "FileCaster", or changing the floppy disk to a new one every time :(
I apologize for possible errors in the text, I do not speak English, but I tried to avoid this.

**Comment by tofodroid** [comment]
Hello! Sorry for taking so long to get to this, life has been super busy recently and I haven't been able to find time for the mod -

I think this is a very good idea and I will be adding something like this soon! Thank you for the suggestion! 😄

**Comment by tofodroid** [comment]
Hello again! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I've just released Beta versions for a major 4.0.0 update for versions 1.19.2-1.20.4 which replaces Broadcasters with a new Server Transmitter block that supports MIDI files provided by the server!

Please let me know if you have any other issues!
