### ISSUE TITLE
[QUESTION] Broadcasting to MIDI Maestro

### ISSUE THREAD

**Issue by TrikiNya** [tofodroid/mimi-mod#83]
**Question**
Am I able to directly broadcast MIDI inputs to the MIDI Maestro? How would I achieve this?

**Environment (if applicable):**
 - OS: Windows 11
 - Mod Version: 3.0.2
 - Minecraft Version: 1.18.2
 - Forge Version: 40.1.80

**Comment by tofodroid** [comment]
Hello! Sorry for taking so long to get to this, life has been super busy recently and I haven't been able to find time for the mod -

Currently there is not a way to do this, but I will look into adding a block or item to the game that would support this!

**Comment by tofodroid** [comment]
Version 4.1.0 has been release including this feature!
