### ISSUE TITLE
[FEATURE] The ability to change an offset for MIDI device velocities

### ISSUE THREAD

**Issue by Molioron** [tofodroid/mimi-mod#86]
**Is your feature request related to a problem? Please describe.**
Some midi keyboards don't have the ability change the offset of their velocities (i.e. pressing keys normally plays relatively quiet notes and there is no button to change that).

**Describe the solution you'd like**
An option in the device config item that allows adding an offset to said velocity such that the final velocity (that will be played) will be offset + device_velocity.

**Describe alternatives you've considered**
Pressing harder can technically solve this problem, but continuously doing so is very annoying.

**Additional context**
N/A

**Comment by tofodroid** [comment]
Hello! Sorry for taking so long to get to this, life has been super busy recently and I haven't been able to find time for the mod -

This is a great idea and I will definitely find a way to incorporate this into the next release! Thanks for the suggestion!

**Comment by tofodroid** [comment]
Version 4.1.0 has been release including this feature!
