### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by revowolfie** [tofodroid/mimi-mod#91]
**Is your feature request related to a problem? Please describe.**
While it may not be a problem, I'm attempting to use the stationary receiver blocks to trigger notes played by the create mod's steam whistles (essentially a pipe organ that can play MIDIs and be controlled through in-game instruments on midi channel 1)

**Describe the solution you'd like**
It would be awesome to be able to configure the redstone output of the receiver when it matches a played note (ie instead of a pulse, the redstone strength, duration, and fade (or envelope) will match the MIDI note's corresponding values) either through a client config or a built-in GUI for the block (and others with similar functionality like the listener, etc.)

**Describe alternatives you've considered**
I've attempted living with the pulses, working with More Red to test some theories with gates, but I can't seem to find a way to loop the signal back in to de-activate the redstone signal and stop the notes. The pulsed redstone unfortunately defeats the purpose of having an organ, but for this build I'd really like to make it work (yes, the mod already has one but it isn't very aesthetically pleasing or large enough to fit the scale of the build).

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I've just released Beta versions for a major 4.0.0 update for versions 1.19.2-1.20.4 which adds a new "Note Held" mode to the Listener and Receiver which should allow for the behavior you're wanting!

Please let me know if you have any other issues!
