### ISSUE TITLE
[QUESTION] Looping Broadcasters

### ISSUE THREAD

**Issue by ajlittle** [tofodroid/mimi-mod#92]
**Question**
Is there any way to loop Broadcaster blocks? Wasn't able to find any documentation on this

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I've just released Beta versions for a major 4.0.0 update for versions 1.19.2-1.20.4 which replaces Broadcasters with a new Server Transmitter block that supports looping!

Please let me know if you have any other issues!
