### ISSUE TITLE
[BUG] 1.20.2 Fails to load with Network Channel Builder def not found.

### ISSUE THREAD

**Issue by majorcyto** [tofodroid/mimi-mod#93]
**Describe the bug**
When loading mimi-mod on any forge version on 1.20.2 minecraft it will fail to load the mod due to not finding the network channel builder. Reverting to 1.20.1 with an appropriate forge version lets the mod load.

**To Reproduce**
1. Download Minecraft 1.20.2
2. Download any version of Forge that supports 1.20.2
3. Start minecraft, experience error.

**Expected behavior**
Load Mod please. :)!

**Screenshots**

**Crash Logs**
If applicable, add log files or crash reports that were generated.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10, MaxOS Big Sur, Ubuntu 21.0.4]
 - Mod Version: [e.g. 1.2.0.RELEASE]
 - Minecraft Version: [e.g. 1.16.5]
 - Forge Version: [e.g. 1.16.5 - 36.1.0]

**Additional context**

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I've just released Beta versions for a major 4.0.0 update for versions 1.19.2-1.20.4 which should resolve this problem! Please let me know if you encounter any other issues!
