### ISSUE TITLE
[FEATURE] The Ability To Have Custom Keymaps

### ISSUE THREAD

**Issue by Hoontarius** [tofodroid/mimi-mod#95]
I have been playing VirtualPiano format piano for many years now, and its a very common format people play in on PC keyboard, and it's kind of sad I can't play it using it with this mod, as it is in my opinion the best of all other instrument mods. The complicated part about it is that is how it uses holding shift to shift half notes (generally to play black keys unless transposed differently) Doing this 100% is understandably a lot of work, especially for something you are most likely completely unfamiliar.

In general just the ability to have an easily configurable map system would be really nice, it is just really important that you can map button combinations to certain keys. (Example: Shift + Q)

If you want more info I would be happy to point you around to some things about this format, in hopes and prayers this resonates with people

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. 

MIMI does actually support the VirtualPiano layout (or at least, I hope it's working 😄). You can change the key layout using the button in the top right of the Instrument Screen.

Let me know if that works for you!
