### ISSUE TITLE
[IMPROVEMENT] Update files on modrinth

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [tofodroid/mimi-mod#96]
**Is your improvement request related to a problem? Please describe.**
Newer versions of the mod are not available on Modrinth, and are only available on Curseforge right now. This is fairly inconvinient when creating modpacks on Modrinth, as you have to manually download the mod first from Curse (and according to the readme, you support Modrinth anyway).

**Describe the solution you'd like**
Upload newer versions of the mod on Modrinth alongside Curseforge

**Additional context**
![image](https://github.com/tofodroid/mimi-mod/assets/66212375/dd361c83-6a87-456a-a86e-3fb79e80d583)
Download page on Modrinth only has files for 1.18 and 1.19

![image](https://github.com/tofodroid/mimi-mod/assets/66212375/6089c1ef-05bc-4e47-909c-d28b4ab8cdd1)
Curseforge has all the versions

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. I was having some issues with uploading to ModRinth the last time I released a big update and I forgot to go back around and try again. I will make sure I get it updated this weekend!

Thanks for the reminder!

**Comment by tofodroid** [comment]
Modrinth has been updated!
