### ISSUE TITLE
[QUESTION] Any way a noob like me could help?

### ISSUE THREAD

**Issue by Merancapeman** [tofodroid/mimi-mod#97]
**Question**
Hey, I see you don't have a discord. I don't have much mod making experience, although I can run a server and know a little of the process. I do, however, have experience working in music editing software and MIDI creation, and I'm playing on a server with the Craft To Exile 2 modpack and there's interest in seeing it integrated. I'd like to learn more and I'm wondering if there's any way I could help to either help keep it updated, help make tutorials, or implement some QOL suggestions I have, for instance the ability to import custom MIDI files into the system to allow for exclusive music sheet/floppy disc creation that doesn't need to rely solely on a URL so that you can trade/sell imported or original songs that can't simply be copied, so a music profession can be a part of a server economy. Not sure if that sounds silly, but either way, this mod is one of the most underrated ones out there and it's unfortunate there's not more documentation behind systems including the music puzzles utilizing listener blocks, or the custom sf2 file integration (it indicates that the filesize might be an issue but there's no telling how big or small the sf2 file needs to be for MC to accept it). Thank you for the genius work behind this!

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod.

I'll reply again with a much more thought out and detailed reply in the next day or so, but I just wanted to reply quickly now to say I really appreciate the interest in helping out and where you can! It means a lot that people are so invested in the mod even when I've had to be away for awhile.

I want to really give your question some thought and come up with some good ways that beginner mod developers can help so I'm going to take some time to think about it. I really appreciate you bringing this up!

**Comment by Merancapeman** [comment]
I believe in the time I made this comment I've learned more about some of the functions and how to implement them, but I'll have to experiment more. I really get the whole "life is super crazy" situation, so no need to apologize. The mod is pretty intuitive and solid, and imo ingenious. No need to rush anything, and I appreciate the response!

**Comment by Merancapeman** [comment]
> Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod.
> 
> I'll reply again with a much more thought out and detailed reply in the next day or so, but I just wanted to reply quickly now to say I really appreciate the interest in helping out and where you can! It means a lot that people are so invested in the mod even when I've had to be away for awhile.
> 
> I want to really give your question some thought and come up with some good ways that beginner mod developers can help so I'm going to take some time to think about it. I really appreciate you bringing this up!

Hey, just thought you might also like to see this video I made using your amazingly genius mod (your recent update just made the interaction in this video possible, so kudos to updating your already awesome mod and by far my favorite Minecraft mod OF ALL TIME), as it now can interact with Create's organ! This is now a must-have mod for any server I want to join/make, so I'll try to help out and make some videos of utilizing its features when I can, if that's ok with you! If need be I can try my hand at making tutorials unless you'd rather make those. Thank you so much for this mod!

https://youtu.be/ECQ2dKiSBsQ

**Comment by tofodroid** [comment]
Wow that's super cool! I never really envisioned MIMI being used to create instruments out of other things within Minecraft but it totally works! Thank you so much for sharing! Making some videos about MIMI (whether it's full tutorials, feature highlights, or just cool stuff you're making) is absolutely a great way to help out! Feel free to send any videos that you make my way and I'll look into sharing and featuring them on the CurseForge and Modrinth pages!

To finally fully answer your original question - I have added a whole bunch more to the "Contributing" section of the README which will hopefully help you and anyone else that is interested in contributing to MIMI in the future! Let me know if you have any feedback or any other ideas that I should add! Thank you again for your support and engagement with the mod!

https://github.com/tofodroid/mimi-mod/blob/main/README.md#contribtuing

**Comment by tofodroid** [comment]
Side-note: I've added a new [issue](https://github.com/tofodroid/mimi-mod/issues/108) for your music sheet/floppy disk idea! That's something I've also wanted to find a way to incorporate into the mod and now that I've got the code in a much cleaner sport I can spend some more time coming up with a way to tackle it.

**Comment by Merancapeman** [comment]
Thank you again, I can't imagine how difficult this mod must be to make but it's right up my alley and making music a part of Minecraft and keeping MIDI alive is super cool and I hope you know that. I'm in the process of making a town for a server that utilizes your mod (Craft to Exile 2) and showcasing the things you can do with it by using it in key aspects of the town, especially with the many things it's just inherently compatible with because it uses redstone perfectly. Create is a great example, because now you can make traps or drawbridges or farming machines operate with a song. That's the coolest thing you could do in Minecraft. It's absolutely brilliant, so thank you for being a part of helping Minecraft be a push to get back into composing again.

**Comment by tofodroid** [comment]
That all sounds awesome! 😄 Excited to see what you create!
