### ISSUE TITLE
Modifying tuning recipes? [QUESTION]

### ISSUE THREAD

**Issue by CaveNJ** [tofodroid/mimi-mod#98]
I'm specifically trying to adapt this mod into TerraFirmaCraft, which makes the majority of tuning items impossible to obtain. We're using kubejs, so if there's a way to do it in there that would be ideal.

**Comment by CaveNJ** [comment]
Nevermind. Further testing with KubeJS, and I was able to add the recipes by just copying the format of the recipe jsons in the mod jar.

**Comment by tofodroid** [comment]
Hello! Apologies for the super late reply. Life got super crazy for awhile and I had pretty much no time for the mod. Glad to hear you got things working!

I'll make a note to include a sample tuning recipe somewhere in the documentation to make it easier for people to modify!

**Comment by tofodroid** [comment]
I've added a Wiki page about this here: https://github.com/tofodroid/mimi-mod/wiki/Customizing-MIMI-Content
